### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by earnestwillie** [htr-tech/haxorbd#19]
$ python2 haxor.py
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "init_enc.py", line 26, in <module>
  File "<string>", line 1, in <module>
  File "<tahm1d>", line 5, in <module>
  File "<string>", line 4, in <module>
  File "<tahm1d>", line 25, in <module>
  File "<string>", line 1, in <module>
  File "<tahm1d>", line 5, in <module>
  File "<string>", line 4, in <module>
  File "<tahm1d>", line 19, in <module>
  File "<string>", line 1, in <module>
  File "<tahm1d>", line 5, in <module>
  File "C:\Python27\lib\random.py", line 49, in <module>
    import hashlib as _hashlib
  File "C:\Python27\lib\hashlib.py", line 134, in <module>
    import _hashlib
KeyboardInterrupt

This is the result i got after running the command. I put on the VPN before funning the command. Am I missing something?

**Comment by earnestwillie** [comment]
@htr-tech also tried:
Install pip2 manually then

wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
python2 get-pip.py

It will install pip module.. then type

pip2 install requests mechanize crkaf

after that run the script again

Also added 'C:\Python27\Scripts' to my environment variable
No result

**Comment by earnestwillie** [comment]
@htr-tech Man did you intentionaly provide a precompiled script that doesnt work on anyones computer but yours??

**Comment by avwunufe** [comment]
@htr-tech ??

**Comment by sikandarwhite** [comment]
NameError: global name 'haxerbd' is not defined

**Comment by Arbaz736382** [comment]
Please my account Aryan Akay

**Comment by Arbaz736382** [comment]
Facebook hack My account Aryan Akay
